### ISSUE TITLE
Cannot convert ‘struct THDoubleTensor *’ to ‘struct THLongTensor *’

### ISSUE THREAD

**Issue by wuwo007** [DeepPep/DeepPep#4]
Hello,
  I have configured my environment in Ubuntu by your description. However, when i run "python run.py  ./data/18mix" or other test datasets, I encountered one error:
![image](https://user-images.githubusercontent.com/14055402/33800953-f0bebe44-dd86-11e7-8417-b0550c5bd190.png)

Have you ever had the same question? How can i make it run? thanks.

**Comment by ameenetemady** [comment]
Hi there was a bug in torch to work around it, revert back your torch to checkout mentioned bellow and reinstall it.
cd ~/torch/pkg/torch; git checkout 1e5a315d03c91286d859512574d3b0b25e12d512; luarocks make rocks/nn-scm-1.rockspec
cd ~/torch/extra/nn; git checkout 1443cd7c2becd793b3d954144dcf4a1bf9947771;   luarocks make rocks/torch-scm-1.rockspec

**Comment by ameenetemady** [comment]
Thanks for your interest. Please let me now if you still have issues. I'll close this for now.
